name: Deploy to S3

on:
  push:
    branches:
      - main  # or whichever branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: List files that will be uploaded
      - name: List static website files
        run: |
          echo "Files that will be uploaded to S3:"
          find . -type f \
            \( -name "*.html" -o -name "*.css" -o -name "*.js" -o -name "*.png" \
            -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.svg" \
            -o -name "*.ico" -o -name "*.woff" -o -name "*.woff2" -o -name "*.ttf" \
            -o -name "*.otf" \) \
            ! -path "./architecture-diagram/*" \
            ! -path "./screenshots/*" \
            ! -name "package*.json"

      # Step 4: Sync only static website files to S3
      - name: Sync static website files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
            --exclude "*" \
            --include "*.html" \
            --include "*.css" \
            --include "*.js" \
            --include "*.png" \
            --include "*.jpg" \
            --include "*.jpeg" \
            --include "*.gif" \
            --include "*.svg" \
            --include "*.ico" \
            --include "*.woff" \
            --include "*.woff2" \
            --include "*.ttf" \
            --include "*.otf" \
            --include "*.json" \
            --exclude "package*.json" \
            --exclude "architecture-diagram/*" \
            --exclude "screenshots/*" \
            --exclude "README.md" \
            --exclude "*.md" \
            --exclude "*.txt" \
            --exclude ".s3ignore" \
            --delete
